waylogout \
	--hide-cancel \
	--screenshots \
	--font="Baloo 2" \
	--effect-blur=7x5 \
	--indicator-thickness=20 \
	--ring-color=000000aa \
	--inside-color=111111aa \
	--text-color=eaeaeaaa \
	--line-color=00000000 \
	--ring-selection-color=FFFFFFaa \
	--inside-selection-color=FFFFFFaa \
	--text-selection-color=eaeaeaaa \
	--line-selection-color=00000000 \
	--suspend-command="systemctl suspend" \
	--hibernate-command="systemctl hibernate" \
	--poweroff-command="systemctl poweroff" \
	--reboot-command="systemctl reboot" \
	--selection-label \
    --fade-in=0.5 \
    --indicator-separation=20 \
    --indicator-radius=80 \
    --indicator-thickness=2
