waylogout \
	--hide-cancel \
	--screenshots \
	--font="Baloo 2" \
	--effect-blur=7x5 \
	--indicator-thickness=20 \
	--ring-color=FFA500 \
	--inside-color=FF8C00 \
	--text-color=FFFFF \
	--line-color=AAAAAA \
	--ring-selection-color=FFFFFF \
	--inside-selection-color=FF9F00 \
	--text-selection-color=FFFFFF \
	--line-selection-color=FFFFFF \
	--suspend-command="systemctl suspend" \
	--hibernate-command="systemctl hibernate" \
	--poweroff-command="systemctl poweroff" \
	--reboot-command="systemctl reboot" \
	--selection-label \
    --fade-in=0.5 \
    --indicator-separation=20 \
    --indicator-radius=80 \
    --indicator-thickness=2
